// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: causa/cgrpc.proto

package org.kjob.remote.api;

public final class CausaGrpcClientGen {
  private CausaGrpcClientGen() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\021causa/cgrpc.proto\032!causa/server_discov" +
      "er_causa.proto2\206\001\n\016ServerDiscover\022\"\n\tass" +
      "ertApp\022\010.AppName\032\t.Response\"\000\022.\n\016heartbe" +
      "atCheck\022\017.HeartbeatCheck\032\t.Response\"\000\022 \n" +
      "\npingServer\022\005.Ping\032\t.Response\"\000B)\n\023org.k" +
      "job.remote.apiB\022CausaGrpcClientGenb\006prot" +
      "o3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          org.kjob.remote.protos.ServerDiscoverCausa.getDescriptor(),
        }, assigner);
    org.kjob.remote.protos.ServerDiscoverCausa.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
